### ISSUE TITLE
テーブル設計

### ISSUE THREAD

**Issue by kokeshi92** [bitswitches/IflavorServer#8]
- ER図に起こしてください。

**Comment by kokeshi92** [comment]
- 12/8まで

**Comment by shotaws** [comment]
https://github.com/bitswitches/IflavorServer/pull/24
タックと山上さんと私で今週月曜日の夜に話し合いながら、作業を進めました。
なお、API設計次第では微調整が入る可能性があります。
山上さんには今週木曜日までに完璧ではなくても良いのでAPI設計のたたきをSwaggerで作るように言いました。

**Comment by shotaws** [comment]
ER図に起こしてfork元にマージされたので、クローズしちゃいます。
